/* insights.js — Extra insights extracted from the slicer's comment blocks (no DOM).
   Reads only the summary/config comments (cheap and reliable). Tuned for OrcaSlicer,
   which writes a big `; key = value` CONFIG_BLOCK at the end of the file, but the
   generic extractors also work for PrusaSlicer/SuperSlicer/Bambu-style comments. */
import { parseHms } from "./parse.js";

// `; some_key = value`  (Orca/Prusa config block). Returns the trimmed value or null.
function cfg(text, key) {
  const m = text.match(new RegExp(";\\s*" + key + "\\s*=\\s*([^\\n\\r]+)", "i"));
  return m ? m[1].trim() : null;
}
function cfgNum(text, key) {
  const v = cfg(text, key);
  if (v == null) return null;
  const n = parseFloat(v);
  return isFinite(n) ? n : null;
}
// `; some key: value`  (Orca HEADER_BLOCK uses a colon). Returns a number or null.
function colonNum(text, key) {
  const m = text.match(new RegExp(";\\s*" + key + "\\s*:\\s*(-?[\\d.]+)", "i"));
  return m ? parseFloat(m[1]) : null;
}

// "0x0,225x0,225x225,0x225" -> { x: 225, y: 225 }
function parseBed(str) {
  if (!str) return null;
  let x = 0, y = 0, re = /(-?[\d.]+)\s*x\s*(-?[\d.]+)/gi, m;
  while ((m = re.exec(str))) { x = Math.max(x, +m[1]); y = Math.max(y, +m[2]); }
  return x || y ? { x, y } : null;
}

// Bed temperature depends on the active plate type in Orca.
const PLATE_KEY = {
  "cool plate": "cool_plate_temp",
  "textured cool plate": "textured_cool_plate_temp",
  "engineering plate": "eng_plate_temp",
  "high temp plate": "hot_plate_temp",
  "smooth pei plate": "hot_plate_temp",
  "textured pei plate": "textured_plate_temp",
  "supertack plate": "supertack_plate_temp",
};

export function parseInsights(text) {
  const t = text || "";
  const o = {};

  // --- Slicer + machine ---
  let m;
  if ((m = t.match(/generated by\s+(Orca[\s-]?Slicer|PrusaSlicer|SuperSlicer|BambuStudio|SuperSlicer)\s*([\d.]+)?/i))) {
    o.slicer = /orca/i.test(m[1]) ? "OrcaSlicer" : m[1];
    o.slicerVersion = m[2] || null;
  }
  o.printerModel = cfg(t, "printer_model");
  o.nozzleDiameter = cfgNum(t, "nozzle_diameter");
  o.gcodeFlavor = cfg(t, "gcode_flavor");
  o.bed = parseBed(cfg(t, "printable_area"));
  o.bedHeight = cfgNum(t, "printable_height");
  o.bedType = cfg(t, "curr_bed_type");

  // --- Print geometry ---
  o.layers = colonNum(t, "total layer number") || cfgNum(t, "total layers count");
  o.layerHeight = cfgNum(t, "layer_height");
  o.firstLayerHeight = cfgNum(t, "initial_layer_print_height") || cfgNum(t, "first_layer_height");
  o.maxZ = colonNum(t, "max_z_height");

  // Times (seconds)
  if ((m = t.match(/estimated printing time\s*\(normal mode\)\s*=\s*([0-9dhms\s]+)/i)))
    o.time = parseHms(m[1]);
  if ((m = t.match(/estimated first layer printing time[^=]*=\s*([0-9dhms\s]+)/i)))
    o.firstLayerTime = parseHms(m[1]);

  // --- Material ---
  o.filamentType = cfg(t, "filament_type");
  o.filamentName = (cfg(t, "filament_settings_id") || "").replace(/^"|"$/g, "") || null;
  o.filamentVendor = cfg(t, "filament_vendor");
  o.density = cfgNum(t, "filament_density") || colonNum(t, "filament_density");
  o.diameter = cfgNum(t, "filament_diameter") || colonNum(t, "filament_diameter");
  o.costPerKg = cfgNum(t, "filament_cost");
  if ((m = t.match(/filament used\s*\[g\]\s*=\s*([\d.,\s]+)/i)))
    o.grams = m[1].split(/[,;]/).reduce((a, x) => a + (parseFloat(x) || 0), 0);
  if ((m = t.match(/filament used\s*\[mm\]\s*=\s*([\d.,\s]+)/i)))
    o.lengthMm = m[1].split(/[,;]/).reduce((a, x) => a + (parseFloat(x) || 0), 0);
  if ((m = t.match(/filament used\s*\[cm3\]\s*=\s*([\d.,\s]+)/i)))
    o.volumeCm3 = m[1].split(/[,;]/).reduce((a, x) => a + (parseFloat(x) || 0), 0);
  if ((m = t.match(/total filament cost\s*=\s*([\d.]+)/i)) ||
      (m = t.match(/;\s*filament cost\s*=\s*([\d.]+)/i)))
    o.slicerCost = parseFloat(m[1]);
  // color/material count from the per-extruder gram list
  if ((m = t.match(/filament used\s*\[g\]\s*=\s*([\d.,\s]+)/i)))
    o.colors = m[1].split(/[,;]/).map((s) => parseFloat(s)).filter((v) => isFinite(v) && v > 0).length || 1;

  // --- Temperatures (°C) ---
  o.nozzleTemp = cfgNum(t, "nozzle_temperature");
  o.nozzleTempFirst = cfgNum(t, "nozzle_temperature_initial_layer");
  const plateKey = PLATE_KEY[(o.bedType || "").toLowerCase()];
  o.bedTemp = (plateKey && cfgNum(t, plateKey)) ?? cfgNum(t, "hot_plate_temp") ?? cfgNum(t, "first_layer_bed_temperature");
  o.bedTempFirst = (plateKey && cfgNum(t, plateKey + "_initial_layer")) ?? cfgNum(t, "first_layer_bed_temperature");

  // --- Quality / structure ---
  o.wallLoops = cfgNum(t, "wall_loops");
  o.topShell = cfgNum(t, "top_shell_layers");
  o.bottomShell = cfgNum(t, "bottom_shell_layers");
  o.infillDensity = cfg(t, "sparse_infill_density");   // e.g. "10%"
  o.infillPattern = cfg(t, "sparse_infill_pattern");
  o.wallSequence = cfg(t, "wall_sequence");
  o.seamPosition = cfg(t, "seam_position");
  o.fuzzySkin = cfg(t, "fuzzy_skin");

  // --- Speeds (mm/s) ---
  o.speedOuterWall = cfgNum(t, "outer_wall_speed");
  o.speedInnerWall = cfgNum(t, "inner_wall_speed");
  o.speedInfill = cfgNum(t, "sparse_infill_speed");
  o.speedTravel = cfgNum(t, "travel_speed");
  o.speedFirstLayer = cfgNum(t, "initial_layer_speed");

  // --- Supports ---
  o.supportEnabled = cfg(t, "enable_support");
  o.supportEnabled = o.supportEnabled == null ? null : o.supportEnabled === "1";
  o.supportType = cfg(t, "support_type");
  o.supportStyle = cfg(t, "support_style");
  o.supportThreshold = cfgNum(t, "support_threshold_angle");

  // --- Adhesion ---
  o.brimType = cfg(t, "brim_type");
  o.brimWidth = cfgNum(t, "brim_width");
  o.skirtLoops = cfgNum(t, "skirt_loops");

  // --- Misc ---
  o.retractionLength = cfgNum(t, "retraction_length");
  o.retractionSpeed = cfgNum(t, "retraction_speed");
  o.zHop = cfgNum(t, "z_hop");

  return o;
}

// True if the parsed insights carry at least the useful slicer-config fields
// (distinguishes a rich Orca/Prusa gcode from a bare one with only a summary).
export function hasRichConfig(o) {
  return !!(o && (o.nozzleTemp != null || o.layerHeight != null || o.wallLoops != null));
}
