import test from "node:test";
import assert from "node:assert/strict";
import * as C from "../src/lib/index.js";

const close = (a, b, eps = 0.005) =>
  assert.ok(Math.abs(a - b) < eps, `expected ~${b}, got ${a}`);

/* A trimmed but faithful OrcaSlicer 2.4.2 gcode (Elegoo Neptune 4 Pro, Klipper):
   header block, the fake Cura line, summary, and a subset of the CONFIG_BLOCK. */
const ORCA = `
; HEADER_BLOCK_START
; generated by Orca-Slicer 2.4.2 on 2026-08-24 at 21:32:50
; Mentioning Cura_SteamEngine X.X to trick printer into thinking this is Cura
; total layer number: 563
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 84.97
; filament: 1
; HEADER_BLOCK_END

;TIME:12480
;TYPE:Custom

; filament used [mm] = 16484.92
; filament used [cm3] = 39.65
; filament used [g] = 49.17
; filament cost = 0.74
; total filament used [g] = 49.17
; total filament cost = 0.74
; total layers count = 565
; estimated printing time (normal mode) = 3h 28m 39s
; estimated first layer printing time (normal mode) = 21s

; CONFIG_BLOCK_START
; brim_type = no_brim
; brim_width = 6
; bottom_shell_layers = 4
; curr_bed_type = High Temp Plate
; enable_support = 1
; filament_cost = 15
; filament_density = 1.24
; filament_diameter = 1.75
; filament_settings_id = "Elegoo PLA - Hugo"
; filament_type = PLA
; filament_vendor = Generic
; fuzzy_skin = disabled_fuzzy
; gcode_flavor = klipper
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; initial_layer_print_height = 0.25
; initial_layer_speed = 60
; inner_wall_speed = 200
; layer_height = 0.16
; max_layer_height = 0.28
; min_layer_height = 0.12
; nozzle_diameter = 0.4
; nozzle_temperature = 210
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 240
; outer_wall_speed = 150
; printable_area = 0x0,225x0,225x225,0x225
; printable_height = 265
; printer_model = Elegoo Neptune 4 Pro
; retraction_length = 0.8
; retraction_speed = 60
; seam_position = aligned
; skirt_loops = 0
; sparse_infill_density = 10%
; sparse_infill_pattern = adaptivecubic
; sparse_infill_speed = 130
; support_style = organic
; support_threshold_angle = 45
; support_type = tree(auto)
; top_shell_layers = 5
; travel_speed = 500
; wall_loops = 2
; wall_sequence = inner-outer-inner wall
; z_hop = 0.4
; z_hop_types = Spiral Lift
; first_layer_bed_temperature = 60
; first_layer_temperature = 220
; first_layer_height = 0.250
; CONFIG_BLOCK_END
`;

/* ---------- slicer detection fix (Orca-Slicer hyphen + Cura trick line) ---------- */
test("parseGcode identifies Orca-Slicer despite the Cura trick line", () => {
  assert.equal(C.parseGcode(ORCA).slicer, "OrcaSlicer");
});

/* ---------- parseInsights: machine + slicer ---------- */
test("parseInsights: slicer, version and printer", () => {
  const o = C.parseInsights(ORCA);
  assert.equal(o.slicer, "OrcaSlicer");
  assert.equal(o.slicerVersion, "2.4.2");
  assert.equal(o.printerModel, "Elegoo Neptune 4 Pro");
  assert.equal(o.nozzleDiameter, 0.4);
  assert.equal(o.gcodeFlavor, "klipper");
  assert.deepEqual(o.bed, { x: 225, y: 225 });
  assert.equal(o.bedHeight, 265);
});

/* ---------- parseInsights: geometry + time ---------- */
test("parseInsights: layers, heights, times", () => {
  const o = C.parseInsights(ORCA);
  assert.equal(o.layers, 563);          // header 'total layer number' wins
  assert.equal(o.layerHeight, 0.16);
  assert.equal(o.firstLayerHeight, 0.25);
  close(o.maxZ, 84.97);
  assert.equal(o.time, 12519);          // 3h 28m 39s, not the fake ;TIME:12480
  assert.equal(o.firstLayerTime, 21);
});

/* ---------- parseInsights: material + cost ---------- */
test("parseInsights: material and slicer cost", () => {
  const o = C.parseInsights(ORCA);
  assert.equal(o.filamentType, "PLA");
  assert.equal(o.filamentName, "Elegoo PLA - Hugo");
  assert.equal(o.filamentVendor, "Generic");
  close(o.density, 1.24);
  close(o.diameter, 1.75);
  close(o.grams, 49.17);
  close(o.lengthMm, 16484.92, 0.1);
  close(o.volumeCm3, 39.65);
  assert.equal(o.costPerKg, 15);
  close(o.slicerCost, 0.74);
  assert.equal(o.colors, 1);
});

/* ---------- parseInsights: temperatures (bed from active plate type) ---------- */
test("parseInsights: temperatures", () => {
  const o = C.parseInsights(ORCA);
  assert.equal(o.nozzleTemp, 210);
  assert.equal(o.nozzleTempFirst, 220);
  assert.equal(o.bedTemp, 60);          // High Temp Plate -> hot_plate_temp
  assert.equal(o.bedTempFirst, 60);
});

/* ---------- parseInsights: quality, speeds, supports, adhesion ---------- */
test("parseInsights: quality and speeds", () => {
  const o = C.parseInsights(ORCA);
  assert.equal(o.wallLoops, 2);
  assert.equal(o.topShell, 5);
  assert.equal(o.bottomShell, 4);
  assert.equal(o.infillDensity, "10%");
  assert.equal(o.infillPattern, "adaptivecubic");
  assert.equal(o.wallSequence, "inner-outer-inner wall");
  assert.equal(o.speedOuterWall, 150);
  assert.equal(o.speedInnerWall, 200);
  assert.equal(o.speedInfill, 130);
  assert.equal(o.speedTravel, 500);
});
test("parseInsights: supports and adhesion", () => {
  const o = C.parseInsights(ORCA);
  assert.equal(o.supportEnabled, true);
  assert.equal(o.supportType, "tree(auto)");
  assert.equal(o.supportStyle, "organic");
  assert.equal(o.supportThreshold, 45);
  assert.equal(o.brimType, "no_brim");
  assert.equal(o.brimWidth, 6);
  assert.equal(o.skirtLoops, 0);
  assert.equal(o.zHop, 0.4);
  assert.equal(o.retractionLength, 0.8);
});

/* ---------- robustness: empty / minimal input ---------- */
test("parseInsights: empty input doesn't throw and returns nulls", () => {
  const o = C.parseInsights("");
  assert.equal(o.nozzleTemp, null);
  assert.equal(o.layers, null);
  assert.equal(C.hasRichConfig(o), false);
});
test("hasRichConfig: true for a real config", () => {
  assert.equal(C.hasRichConfig(C.parseInsights(ORCA)), true);
});
